import 'react';
import 'react-dom';
import 'react-router-dom';
import 'prop-types';
import 'raphael';
import { add, subtract } from 'mathjs';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/fromEvent';
import 'rxjs/add/observable/combineLatest';
import 'rxjs/add/operator/startWith';
import 'rxjs/add/operator/map';
import 'lodash/isEqual';
