import 'react';
import 'react-dom';
import 'react-router-dom';
import 'prop-types';
import 'react-addons-css-transition-group';
import 'raphael';
import { add, divide, subtract, multiply } from 'mathjs';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/fromEvent';
import 'rxjs/add/observable/timer';
import 'rxjs/add/observable/combineLatest';
import 'rxjs/add/operator/startWith';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/do';
import 'lodash/isEqual';
